---

- hosts: jumpbox
  gather_facts: false
  tasks:
   - name: Fetch Instance Info
     os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
     register: result
     tags: always
   - name: Add host to
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
     with_items: "{{result.ansible_facts.openstack_servers}}"
     tags: always
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
     with_items: "{{result.ansible_facts.openstack_servers}}"
     tags: always

- hosts: all
  roles:
    - role: common
      tags: common

- name: deploy frontend
  hosts: frontends
  become: true
  roles:
    - role: frontend
      tags: frontend

- name: deploy app
  hosts: apps
  become: true
  roles:
    - role: app
      tags: app

- name: deploy db
  hosts: appdbs
  become: true
  roles:
#    - role: db
    - role: geerlingguy.postgresql
      tags: db


