security_groups:
 - name: ICMP_and_SSH
   description: ICMP and SSH enabled
 - name: HTTP_and_HTTPS
   description: HTTP and HTTPS enabled
 - name: TOMCAT
   description: TOMCAT enabled
 - name: POSTGRES
   description: POSTGRES enabled


security_group_rules:
 - security_group: ICMP_and_SSH
   protocol: tcp
   port_range_min: 22
   port_range_max: 22
   remote_ip_prefix: 0.0.0.0/0
 - security_group: ICMP_and_SSH
   protocol: tcp
   port_range_min: 80
   port_range_max: 80
   remote_ip_prefix: 0.0.0.0/0
 - security_group: ICMP_and_SSH
   protocol: icmp
   port_range_min: 0
   port_range_max: 0
   remote_ip_prefix: 0.0.0.0/0
 - security_group: HTTP_and_HTTPS
   protocol: tcp
   port_range_min: 80
   port_range_max: 80
   remote_ip_prefix: 0.0.0.0/0
 - security_group: HTTP_and_HTTPS
   protocol: tcp
   port_range_min: 443
   port_range_max: 443
   remote_ip_prefix: 0.0.0.0/0
 - security_group: TOMCAT
   protocol: tcp
   port_range_min: 8080
   port_range_max: 8080
   remote_ip_prefix: 0.0.0.0/0
 - security_group: POSTGRES
   protocol: tcp
   port_range_min: 5432
   port_range_max: 5432
   remote_ip_prefix: 0.0.0.0/0

ssh_keyname: ansible_ssh
ssh_keyfile: test_id_rsa

